easy_admin:
  site_name: 'Admin'
  design:
    assets:
      js:
        - 'build/js/bootstrap-datepicker.js'
        - 'build/js/bootstrap-datepicker.fr.js'
        - 'build/js/app.js'
        - 'build/runtime.js'
      css:
        - 'build/css/bootstrap-datepicker.css'
        - 'build/css/admin.css'
        - 'build/css/dashboard.css'
        - 'build/css/report.css'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - 'bundles/EasyAdminBundle/form.html.twig'
    menu:
      - { label: 'Home', url: '/', icon: 'home' }

      - { label: 'Dashboard', url: '/admin/dashboard', icon: 'chart-bar', default: true }
      - { label: 'Report', url: '/admin/report', icon: 'calendar-alt' }

      - { label: 'Invoicing' }
      - { entity: 'Invoice', label: 'Invoices', icon: 'coins' }
      - { entity: 'Purchase', label: 'Purchases', icon: 'credit-card' }
      - { entity: 'Declaration', label: 'Declarations', icon: 'landmark' }
      - { entity: 'Activity', label: 'Activities', icon: 'calendar-check' }
      - { entity: 'Company', label: 'Companies', icon: 'building' }
      - { entity: 'Person', label: 'Persons', icon: 'users' }

      - { label: 'Resume' }
      - { entity: 'Experience', label: 'Experiences', icon: 'map-marker-alt' }
      - { entity: 'Skill', label: 'Skills', icon: 'fill-drip' }
      - { entity: 'Attribute', label: 'Attributes', icon: 'address-card' }
      - { entity: 'Hobby', label: 'Hobbies', icon: 'chess' }
      - { entity: 'Education', label: 'Educations', icon: 'graduation-cap'  }
      - { entity: 'Link', label: 'Links', icon: 'link' }

      - { label: 'Other' }
      - { label: 'Invoices book', url: '/admin/invoice/csv', icon: 'file-excel' }
  formats:
    date: 'd/m/Y'
  list:
    max_results: 30
  entities:
    Company:
      class: App\Entity\Company
      controller: App\Controller\CompanyController
      form:
        fields:
          - { type: 'group', columns: 3, label: 'Principal' }
          - name
          - { property: 'displayName', label: 'Display name' }
          - { property: 'type', type: 'choice', type_options: { choices: !php/const App\Entity\Company::TYPES } }
          - { type: 'group', columns: 3, label: 'Hierarchy' }
          - { property: 'clients', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { property: 'contractor', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { property: 'persons', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Person', attr: { create: true } } }
          - { type: 'group', columns: 3, label: 'Address' }
          - street
          - postalCode
          - city
          - { type: 'group', columns: 3, label: 'Notes' }
          - notes
          - { type: 'group', columns: 12, label: 'Experiences' }
          - { property: experiences, label: '', type: embedded_list }
          - { type: 'group', columns: 12, label: 'Invoices' }
          - { property: invoices, label: '', type: embedded_list }
      list:
        fields:
          - { property: 'displayName', label: 'Name' }
          - { property: 'typeName', label: 'Type' }
          - { property: 'client', type: 'association', targetEntity: 'App\Entity\Company', associationType: !php/const Doctrine\ORM\Mapping\ClassMetadataInfo::MANY_TO_ONE }
          - contractor
          - { property: 'persons', type: 'array' }
          - notes
        filters:
          - { property: type, type: 'App\Form\Filter\CompanyTypeFilterType' }
        max_results: 20
    Person:
      class: App\Entity\Person
      form:
        fields:
          - { property: 'company' }
          - { property: 'civility', type: 'choice', type_options: { choices: !php/const App\Entity\Person::CIVILITIES } }
          - firstname
          - lastname
          - email
          - phones
          - isInvoicingDefault
      list:
        fields:
          - company
          - { property: civilityName, label: 'Civility' }
          - firstname
          - lastname
          - email
          - phones
    Invoice:
      class: App\Entity\Invoice
      controller: App\Controller\InvoiceController
      form:
        fields:
          - { type: 'group', columns: 2 }
          - number
          - { type: 'group', columns: 4 }
          - object
          - { type: 'group', columns: 3 }
          - { property: 'company', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { type: 'group', columns: 3 }
          - { property: 'experience', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Experience' } }
          - { type: 'group', columns: 2, label: 'Invoicing' }
          - { property: 'daysCount', type: 'number'}
          - tjm
          - { type: 'group', columns: 2, label: 'Extra' }
          - extraLibelle
          - extraHt
          - { type: 'group', columns: 2, label: 'Calculated' }
          - totalHt
          - totalTax
          - { type: 'group', columns: 2, label: 'Date' }
          - { property: 'createdAt', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - { type: 'group', columns: 2, label: 'Payment' }
          - { property: 'payedBy', type: 'choice', type_options: { choices: !php/const App\Entity\Invoice::PAYED_BYS } }
          - { property: 'payedAt', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' }} }
          - { type: 'group', columns: 2, label: 'Payment' }
          - { property: 'status', type: 'choice', type_options: { choices: !php/const App\Entity\Invoice::STATUES } }
          - period
          - { type: 'group', columns: 12, label: 'Report' }
          - { property: activities, label: '', type: embedded_list }
        actions:
          - { name: 'pdf', target: '_blank', label: 'Pdf', icon: 'file-pdf', css_class: 'btn btn-secondary'}
          - { name: 'validate', label: 'Validate', icon: 'check', css_class: 'btn btn-secondary'}
      show:
        actions:
          - { name: 'pdf', target: '_blank', label: 'Pdf', icon: 'file-pdf', css_class: 'btn btn-secondary'}
          - { name: 'validate', label: 'Validate', icon: 'check', css_class: 'btn btn-secondary'}
          - { name: 'send', label: 'Send', icon: 'envelope', css_class: 'btn btn-danger'}
      list:
        fields:
          - number
          - company
          - experience
          - { property: 'totalTtc', format: '%.0f' }
          - { property: 'totalNet', format: '%.0f' }
          - { property: 'totalHt', format: '%.0f' }
          - { property: 'totalTax', format: '%.0f' }
          - daysCount
          - createdAt
          - payedAt
          - period
          - { property: 'socialDeclaration', label: 'Declarations' }
        sort: [ 'createdAt', 'DESC' ]
        filters:
          - company
          - { property: status, type: 'App\Form\Filter\InvoiceStatusFilterType' }
          - { property: createdAtYear, mapped: false, type: 'App\Form\Filter\DateYearFilterType', type_options: {data: 'createdAt'} }
          - { property: createdAtQuarter, mapped: false, type: 'App\Form\Filter\DateQuarterFilterType', type_options: {data: 'createdAt'} }
          - { property: payedAtYear, mapped: false, type: 'App\Form\Filter\DateYearFilterType', type_options: {data: 'payedAt'} }
          - { property: payedAtQuarter, mapped: false, type: 'App\Form\Filter\DateQuarterFilterType', type_options: {data: 'payedAt'} }
        actions:
          - { name: 'pdf', target: '_blank', label: 'Pdf'}
          - { name: 'validate', label: 'Validate'}
          - { name: 'send', label: 'Send'}
        collapse_actions: true
    Purchase:
      class: App\Entity\Purchase
      controller: App\Controller\PurchaseController
      form:
        fields:
          - number
          - { property: 'payedAt', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: { data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - period
          - totalHt
          - totalTax
          - { property: 'proofFile', type: 'file' }
          - proofData
        actions:
          - { name: 'ocr', label: 'Ocr', icon: 'eye', css_class: 'btn btn-secondary'}
      list:
        fields:
          - payedAt
          - period
          - totalHt
          - totalTax
          - totalTtc
          - { property: 'proof', type: 'image', base_path: '%PROOF_DIRECTORY%' }
        actions:
          - { name: 'ocr', label: 'Ocr'}
    Declaration:
      class: App\Entity\Declaration
      controller: App\Controller\DeclarationController
      form:
        fields:
          - { type: 'group', columns: 3, label: '' }
          - { property: 'type', type: 'choice', type_options: { choices: !php/const App\Entity\Declaration::TYPES } }
          - { type: 'group', columns: 3, label: '' }
          - period
          - { type: 'group', columns: 3, label: '' }
          - revenue
          - { type: 'group', columns: 3, label: '' }
          - tax
          - { type: 'group', columns: 3, label: '' }
          - { property: 'status', type: 'choice', type_options: { choices: !php/const App\Entity\Declaration::STATUSES } }
          - { type: 'group', columns: 3, label: '' }
          - { property: 'payedAt', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: { data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - { type: 'group', columns: 12, label: 'Invoices' }
          - { property: invoices, label: '', mapped: false, type_options: { block_name: 'invoices_array_with_total' } }
          #- { type: 'group', columns: 12, label: 'Purchases' }
          #- { property: purchases, label: '', mapped: false, type_options: { block_name: 'purchases_array_with_total' } }
        actions:
          - { name: 'calculate', label: 'Recalculate', icon: 'calculator', css_class: 'btn btn-secondary'}
          - { name: 'validate', label: 'Validate', icon: 'check', css_class: 'btn btn-secondary'}
      list:
        fields:
          - type
          - revenue
          - { property: 'revenue', format: '%.0f' }
          - { property: 'tax', format: '%.0f' }
          - { property: 'rate', format: '%.2f' }
          - period
          - status
        sort: ['period', 'DESC']
        actions:
          - { name: 'calculate', label: 'Recalculate'}
          - { name: 'validate', label: 'Validate'}
        filters:
          - { property: status, type: 'App\Form\Filter\DeclarationStatusFilterType' }
          - { property: type, type: 'App\Form\Filter\DeclarationTypeFilterType' }
          - period
    Period:
      class: App\Entity\Period
    Activity:
      class: App\Entity\Activity
      form:
        fields:
          - { property: 'company',  type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company' } }
          - value
          - { property: 'date', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - invoice
      list:
        fields:
          - company
          - value
          - date
          - invoice
        filters:
          #- company
          #- invoice
          - { property: dateYear, mapped: false, type: 'App\Form\Filter\DateYearFilterType', type_options: {data: 'date'} }
          - { property: dateMonth, mapped: false, type: 'App\Form\Filter\DateMonthFilterType', type_options: {data: 'date'} }
        batch_actions:
          - delete
    Experience:
      class: App\Entity\Experience
      controller: App\Controller\ExperienceController
      form:
        fields:
          - { type: 'group', columns: 4, label: 'Principal' }
          - title
          - description
          - { property: 'company', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { property: 'client', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { type: 'group', columns: 4, label: 'Date' }
          - { property: 'dateBegin', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - { property: 'dateEnd', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - { type: 'group', columns: 4, label: 'Options' }
          - { property: 'skills', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Skill', attr: { create: true } } }
          - isFreelance
          - onSite
          - onHomepage
      list:
        fields:
          - company
          - client
          - dateBegin
          - dateEnd
          - onHomepage
        batch_actions:
          - update
    Skill:
      class: App\Entity\Skill
      form:
        fields:
          - name
          - { property: 'type', type: 'choice', type_options: { choices: !php/const App\Entity\Skill::TYPES } }
          - { property: 'level', type_options: {attr: {min: 0, max: 10 } } }
          - { property: 'parent', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Skill', attr: { create: true } } }
          - onHomepage
          - experiences
      list:
        fields:
          - name
          - { property: 'typeName', label: 'Type' }
          - level
          - parent
          - onHomepage
    Attribute:
      class: App\Entity\Attribute
      form:
        fields:
          - slug
          - { property: 'value', type: 'textarea' }
          - icon
          - weight
          - isListable
      list:
        fields:
          - slug
          - value
          - isListable
          - weight
    Hobby:
      class: App\Entity\Hobby
      form:
        fields:
          - name
      list:
        fields:
          - name
        sort: ['name', 'DESC']
    Link:
      class: App\Entity\Link
      form:
        fields:
          - icon
          - name
          - url
      list:
        fields:
          - name
          - { property: 'url', type: 'url' }
        sort: ['name', 'DESC']
    Education:
      class: App\Entity\Education
      form:
        fields:
          - name
          - school
          - details
          - location
          - level
          - { property: 'dateBegin', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
          - { property: 'dateEnd', type_options: { widget: 'single_text', html5: false, format: 'dd/MM/yyyy', attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr' } } }
      list:
        fields:
          - name
          - school
          - location
          - level
          - dateBegin
          - dateEnd

easy_admin_extension:
  minimum_role: ROLE_ADMIN
