vich_uploader:
    db_driver: orm

    mappings:
        purchases:
            uri_prefix: '%env(DIRECTORY_PURCHASE)%'
            upload_destination: '%kernel.project_dir%/public/upload/%env(DIRECTORY_PURCHASE)%'
        recipes:
            uri_prefix: '%env(DIRECTORY_RECIPE)%'
            upload_destination: '%kernel.project_dir%/public/upload/%env(DIRECTORY_RECIPE)%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }
