#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

redirect:
    path: /fr/{all}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true
    requirements:
        all: ".+"

authentication_token:
    path: /authentication_token
    methods: ['POST']