easy_admin:
  site_name: 'Admin'
  design:
    assets:
      js:
        - 'build/js/bootstrap-datepicker.js'
        - 'build/js/bootstrap-datepicker.fr.js'
        - 'build/js/app.js'
        - 'build/runtime.js'
      css:
        - 'build/css/bootstrap-datepicker.css'
        - 'build/css/dashboard.css'
    menu:
        - { label: 'Home', url: '/' }
        - { label: 'Dashboard', url: '/admin/dashboard' }
        - { label: 'Main' }
        - Companies
        - Persons
        - Experiences
        - Skills
        - Invoices
        - { label: 'Secondary' }
        - Attributes
        - Hobbies
        - Educations
        - Links
  formats:
    date: 'd/m/Y'
  list:
    max_results: 100
  entities:
    Companies:
      class: App\Entity\Company
      form:
        fields:
          - { type: 'group', columns: 3, label: 'Principal' }
          - name
          - displayName
          - { property: 'displayName', label: 'Name' }
          - { type: 'group', columns: 3, label: 'Hierarchy' }
          - { property: 'client', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { property: 'contractor', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { property: 'persons', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Person', attr: { create: true } } }
          - { type: 'group', columns: 6, label: 'Address' }
          - street
          - postalCode
          - city
          - { type: 'group', columns: 12, label: 'Invoices' }
          - { property: invoices, label: '', type: embedded_list }
      list:
        fields:
          - displayName
          - city
          - client
          - contractor
          - persons
    Persons:
      class: App\Entity\Person
      form:
        fields:
          - company
          - { property: 'civility',
              type: 'choice', type_options: {
              choices: {
                M: 'h',
                Mme: 'f',
              }
            } }
          - firstname
          - lastname
          - email
          - phones
      list:
        fields:
          - company
          - civility
          - firstname
          - lastname
          - email
          - phones
    Invoices:
      class: App\Entity\Invoice
      controller: App\Controller\InvoiceController
      form:
        fields:
          - { type: 'group', columns: 3, label: 'Principal' }
          - number
          - { property: 'experience', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Experience', attr: { create: true } } }
          - { type: 'group', columns: 3, label: 'Invoicing' }
          - { property: 'company', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - totalHt
          - totalTax
          - { property: 'daysCount', type: 'number'}
          - { type: 'group', columns: 3, label: 'Date' }
          - { property: 'createdAt',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'payedAt',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { type: 'group', columns: 3, label: 'Payment' }
          - { property: 'payedBy',
                type: 'choice', type_options: {
              choices: {
                Check: 'check',
                Transfert: 'transfert',
              } } }
          - { property: 'status',
              type: 'choice', type_options: {
              choices: {
                Draft: 'draft',
                Waiting: 'waiting',
                Payed: 'payed',
              } } }
      list:
        fields:
          - number
          - company
          - experience
          - { property: 'totalHt', format: '%.0f' }
          - daysCount
          - createdAt
        filters:
          - company
          - { property: status, type: 'App\Form\Filter\InvoiceStatusFilterType' }
          - { property: createdAtYear, mapped: false, type: 'App\Form\Filter\DateYearFilterType', type_options: {data: 'createdAt'} }
          - { property: createdAtQuarter, mapped: false, type: 'App\Form\Filter\DateQuarterFilterType', type_options: {data: 'createdAt'} }
    Experiences:
      class: App\Entity\Experience
      form:
        fields:
          - { type: 'group', columns: 4, label: 'Principal' }
          - title
          - description
          - { property: 'company', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Company', attr: { create: true } } }
          - { type: 'group', columns: 4, label: 'Date' }
          - { property: 'dateBegin',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'dateEnd',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { type: 'group', columns: 4, label: 'Options' }
          - { property: 'skills', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Skill', attr: { create: true } } }
          - isFreelance
          - onSite
          - onHomepage
      list:
        fields:
          - company
          - dateBegin
          - dateEnd
          - onHomepage
    Skills:
      class: App\Entity\Skill
      form:
        fields:
          - name
          - { property: 'type',
              type: 'choice', type_options: {
              choices: {
                Software: 'software',
                Framework: 'framework',
                Platform: 'platform',
                Language: 'language',
                OS: 'os',
              } } }
          - { property: 'level', type_options: {attr: {min: 0, max: 10 } } }
          - { property: 'parent', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Skill', attr: { create: true } } }
          - onHomepage
          - experiences
      list:
        fields:
          - name
          - { property: 'typeName', label: 'Type' }
          - level
          - parent
          - onHomepage
    Attributes:
      class: App\Entity\Attribute
      form:
        fields:
          - icon
          - slug
          - value
          - weight
      list:
        fields:
          - slug
          - value
          - weight
    Hobbies:
      class: App\Entity\Hobby
      form:
        fields:
          - name
      list:
        fields:
          - name
        sort: ['name', 'DESC']
    Links:
      class: App\Entity\Link
      form:
        fields:
          - icon
          - name
          - url
      list:
        fields:
          - name
          - { property: 'url', type: 'url' }
        sort: ['name', 'DESC']
    Educations:
      class: App\Entity\Education
      form:
        fields:
          - name
          - school
          - details
          - location
          - level
          - { property: 'dateBegin',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'dateEnd',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
      list:
        fields:
          - name
          - school
          - location
          - level
          - dateBegin
          - dateEnd

easy_admin_extension:
  minimum_role: ROLE_ADMIN