easy_admin:
  site_name: 'Admin'
  design:
    assets:
      js:
        - 'build/js/bootstrap-datepicker.js'
        - 'build/js/bootstrap-datepicker.fr.js'
        - 'build/js/app.js'
        - 'build/runtime.js'
      css:
        - 'build/css/bootstrap-datepicker.css'
  formats:
    date: 'd/m/Y'
  list:
    max_results: 100
  entities:
    Company:
      class: App\Entity\Company
      form:
        fields:
          - name
          - displayName
          - { property: 'displayName', label: 'name' }
          - location
          - client
          - contractor
            - street
            - postalCode
            - city
      list:
        fields:
          - displayName
          - location
          - client
          - contractor
          - people
    Persons:
      class: App\Entity\Person
      form:
        fields:
          - company
          - { property: 'civility',
              type: 'choice', type_options: {
              choices: {
                M: 'h',
                Mme: 'f',
              } } }
          - firstname
          - lastname
          - email
          - phones
      list:
        fields:
          - company
          - civility
          - firstname
          - lastname
          - email
          - phones
    Invoice:
      class: App\Entity\Invoice
      controller: App\Controller\InvoiceController
      form:
        fields:
          - number
          - company
          - experience
          - totalHt
          - totalTax
          - daysCount
          - { property: 'createdAt',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'payedAt',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'payedBy',
                type: 'choice', type_options: {
              choices: {
                Check: 'check',
                Transfert: 'transfert',
              } } }
          - { property: 'status',
              type: 'choice', type_options: {
              choices: {
                Draft: 'draft',
                Waiting: 'waiting',
                Payed: 'payed',
              } } }
      list:
        fields:
          - number
          - company
          - experience
          - { property: 'totalHt', format: '%.0f' }
          - daysCount
          - createdAt
          - payedAt
    Experience:
      class: App\Entity\Experience
      form:
        fields:
          - title
          - description
          - company
          - isFreelance
          - onSite
          - onHomepage
          - { property: 'dateBegin',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'dateEnd',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - skills
      list:
        fields:
          - company
          - dateBegin
          - dateEnd
          - onHomepage
    Skill:
      class: App\Entity\Skill
      form:
        fields:
          - name
          - { property: 'type',
              type: 'choice', type_options: {
              choices: {
                Software: 'software',
                Framework: 'framework',
                Platform: 'platform',
                Language: 'language',
                OS: 'os',
              } } }
          - { property: 'level', type_options: {attr: {min: 0, max: 10 } } }
          - parent
          - onHomepage
          - experiences
      list:
        fields:
          - name
          - { property: 'typeName', label: 'Type' }
          - level
          - parent
          - onHomepage
    Attribute:
      class: App\Entity\Attribute
      form:
        fields:
          - icon
          - slug
          - value
          - weight
      list:
        fields:
          - slug
          - value
          - weight
    Hobby:
      class: App\Entity\Hobby
      form:
        fields:
          - name
      list:
        fields:
          - name
        sort: ['name', 'DESC']
    Link:
      class: App\Entity\Link
      form:
        fields:
          - icon
          - name
          - url
      list:
        fields:
          - name
          - { property: 'url', type: 'url' }
        sort: ['name', 'DESC']
    Education:
      class: App\Entity\Education
      form:
        fields:
          - name
          - school
          - details
          - location
          - level
          - { property: 'dateBegin',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
          - { property: 'dateEnd',
              type_options: {
                widget: 'single_text', format: 'dd/MM/yyyy',
                attr: {data-provide: 'datepicker', data-date-format: 'dd/mm/yyyy', data-date-language: 'fr'}
              } }
      list:
        fields:
          - name
          - school
          - location
          - level
          - dateBegin
          - dateEnd
