fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "achain.jeremy@gmail.com"
    sender_name: "achain.jeremy@gmail.com"

  registration:
    confirmation:
      from_email:
        address: "achain.jeremy@gmail.com"
        sender_name: "achain.jeremy@gmail.com"

  resetting:
    email:
      from_email:
        address: "achain.jeremy@gmail.com"
        sender_name: "achain.jeremy@gmail.com"