isometriks_spam:
  timed:
    min: 7
    max: 3600
    global: false
    # message also takes translator strings.
    message: You're doing that too quickly.
  honeypot:
    field: email_address
    use_class: false
    hide_class: hidden
    global: false
    message: Form fields are invalid