vich_uploader:
    db_driver: orm

    mappings:
        statements:
            uri_prefix: '%env(DIRECTORY_STATEMENT)%'
            upload_destination: '%kernel.project_dir%/data/%env(DIRECTORY_STATEMENT)%'
        consumptions:
            uri_prefix: '%env(DIRECTORY_CONSUMPTION)%'
            upload_destination: '%kernel.project_dir%/data/%env(DIRECTORY_CONSUMPTION)%'
