name: resume

type: php:7.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - pdo_pgsql
        

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

relationships:
    database: "database_resume:postgresql"
