name: resume

type: php:7.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - pdo_pgsql
        

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "/public/upload": { source: local, source_path: uploads }

dependencies:
    nodejs:
        yarn: "*"

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)
        (>&2
            # Setup everything to use the Node installation
            unset NPM_CONFIG_PREFIX
            export NVM_DIR=$HOME/.nvm
            yarn-install
            set +x && . "${NVM_DIR}/nvm.sh" use --lts && set -x
            # Starting from here, everything is setup to use the same Node
            yarn encore production
        )

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
        
    post_deploy: |
        symfony console doctrine:schema:update --force
        symfony console doctrine:fixtures:load
        
relationships:
    database: "db_resume:postgresql"
