name: resume

type: php:7.3

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - pdo_pgsql


build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 1024

mounts:
    "/var": { source: local, source_path: var }
    #"/vendor/mpdf/mpdf/tmp": { source: local, source_path: tmp_mpdf }
    #"/vendor/dompdf/dompdf/lib/fonts": { source: local, source_path: tmp_dompdf }
    "/public/upload": { source: local, source_path: uploads }

variables:
    env:
        APP_VERSION: 1

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
        apt-get install libfontconfig zlib1g libfreetype6 libxrender1 libxext6 libx11-6
        wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
        tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
        ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin

    post_deploy: |
        symfony console doctrine:schema:update --force
        symfony console doctrine:fixtures:load --env=dev
        
relationships:
    database: "db_resume:postgresql"
