#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

homepage:
    path: /fr/
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true