"http://{all}":
  type: redirect
  to: "https://{all}/"

"https://{all}/":
  type: upstream
  # Route requests to the "app" application
  # "app" is the name defined in .symfony.cloud.yaml
  upstream: "resume:http"