name: resume

type: php:7.3

runtime:
    extensions:
        - mbstring
        - sodium
        - pdo_pgsql

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 1024

mounts:
    "/var": { source: local, source_path: var }
    "/tmp": { source: local, source_path: tmp }
    "/data/invoices": { source: local, source_path: invoices }
    "/public/upload": { source: local, source_path: uploads }

variables:
    env:
        APP_VERSION: 1

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

    post_deploy: |
        symfony console doctrine:schema:update --force
        
relationships:
    database: "db_resume:postgresql"

crons:
    notifications:
        # every monday at 9 AM
        spec: '0 9 * * 1'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape php bin/console app:notifications
            fi

    snapshot:
        # everyday at 5 AM
        spec: '0 5 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape symfony env:snapshot:create --no-wait
            fi

    renewcert:
        # Force a redeploy at 10 AM (UTC) on the 1st and 15th of every month.
        # for the master branch, aka production
        spec: '0 10 1,15 * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape symfony redeploy --no-wait
            fi
